### ISSUE TITLE
KITTI data projector

### ISSUE THREAD

**Issue by niosus** [yorsh87/nicp#2]
I was wondering if you have been using your library with any Velodyne 64 data yet.

I am trying to do this, but the parameters of a spherical projector seem to be wrong. You can see, that the data looks like a paraboloid.
![screenshot from 2016-12-13 16 10 15](https://cloud.githubusercontent.com/assets/1893598/21145555/028acc08-c14f-11e6-8470-5d6225f07332.png)
![screenshot from 2016-12-13 16 10 03](https://cloud.githubusercontent.com/assets/1893598/21145556/02a58b6a-c14f-11e6-80cc-3a7412db5977.png)

I have set the parameters to:
- Horizontal FOV: `3.14`
- Vertical FOV: `0.23` (half of 26&deg;)

I have tried to modify the vertical center from a new ui control `sph_vertical_center_doubleSpinBox` as follows:
```
_sphericalProjector->setVerticalCenter(sph_vertical_center_doubleSpinBox->value());
```
This seems to produce no visible change in the projected cloud with any value from -10 to 10 that I have tried. Should it change anything? Did I misunderstand the purpose of this setting?

 The data is generated by a 64 beam Velodyne that has vertical scan angles from -24&deg; to 2&deg; and the depth image is `64x870`. Here is an example one:
![scan00007](https://cloud.githubusercontent.com/assets/1893598/21145831/f206e1c2-c14f-11e6-9354-8d6077f1e509.png) 
You can get all of them from [here](http://www.mrt.kit.edu/z/publ/download/velodyneslam/data/scenario1.zip). The images are all scaled by 500 as far as I remember. The function to get a `CV_32F` `cv::Mat` with readings in meters from such an image:
```
cv::Mat MatFromDepthPng(const string& path) {
  cv::Mat depth_image = cv::imread(path, CV_LOAD_IMAGE_ANYDEPTH);
  depth_image.convertTo(depth_image, CV_32F);
  depth_image /= 500.;
  return depth_image;
}
```

**Comment by yorsh87** [comment]
I solved the issue, basically before you were not allowed to modify the vertical/horizontal center.

I updated the code and now should work smoothly, however you need to define the correct vertical and horizontal centers if you want to load a consistent cloud.

In the case of KITTI you linked me the vertical center coincides with the 0 deg of the vertical field of view. This can be computed as

vertical_center = deg_offset * num_rows/vertical_fov;

In the case of KITTI this number was

vertical_center = deg2rad(2) * 64 / deg2rad(26) = 4.92308

This number means that the 0 on the vertical fov is located at row 4.92308.

I also updated the GUI removing the cylindrical projector that was obsolete, and adding the fields for the vertical/horizontal centers of the spherical projector, and two additional missing parameters: the lambda for the damped system used during the alignment, and the scaling to apply when reading the depth image (in the case of KITTI 0.002).

I also tested some registrations and they worked smoothly despite the sparse data.

If you want to test the thing I attach you here two screenshots so you can see the parameters I used.

![fly](https://cloud.githubusercontent.com/assets/2599538/21161660/c99741a2-c189-11e6-937e-12f8413f8e95.png)
  
![side](https://cloud.githubusercontent.com/assets/2599538/21161667/d7e0befa-c189-11e6-9281-47480d2569fa.png)

**Comment by niosus** [comment]
Thanks a lot! Exactly what I needed. :+1:
