### ISSUE TITLE
Spaces vs tabs

### ISSUE THREAD

**Issue by niosus** [yorsh87/nicp#3]
Its mostly nitpicking, but you seem to mix tabs and spaces in the code. E.g. line [here](https://github.com/yorsh87/nicp/blob/master/nicp/nicp_viewer/nicp_qglviewer.cpp#L134) has tabs, while everything around it has spaces. It makes the code hard to contribute to as many edits have to be made to unrelated areas. 

I think your emacs puts a single tab character as soon as you reach its size. Would you mind forbidding this and using either tabs or spaces consistently?

**Comment by yorsh87** [comment]
I do not know if it is Emacs producing this, or it is just due to editing with other editors since sometimes happened that I was not able to use emacs. Nitpicking or not I will check it as soon as I can.
